name: '01. Create Eide Bailly Customer App'

run-name: "Create a new Customer Extension App in the Eide Bailly organization"

on:
  workflow_dispatch:
    inputs:
        reponame:
          description: New Repo Name
          required: true

permissions:
  actions: read
  contents: write
  id-token: write
  pull-requests: write

jobs:
  CreateEideBaillyCustomerApp:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repository
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.REPO_ACCESS_TOKEN }}"

      - name: Create new repository
        run: gh repo create EideBaillyCloud/${{ github.event.inputs.reponame }} --private --clone
      
      - name: Set up Git user
        run: |
          git config --global user.name "Eide Bailly Actions"
          git config --global user.email "actions@eidebailly.com"

      # Copy files from the current repostiroy to the new repository
      - name: Copy repository files
        run: |
          cd ${{ github.event.inputs.reponame }}
          rsync -av --exclude="${{ github.event.inputs.reponame }}" ../ ./

      - name: List dir contents
        run: ls -la ./${{ github.event.inputs.reponame }}

      - name: Commit to Git
        run: |
          cd ${{ github.event.inputs.reponame }}
          git add .
          git commit -m "Initiailze repostiroy with template"
          git push origin main